package cn.sw.study.utils.enums;

import cn.sw.study.utils.TableUtils;

/**
 *
 */
public enum TableEnum {

	BUILD_INFO(0,"BUILD_INFO"),

	BUILD_TICKET_USE_INFO(1,"BUILD_TICKET_USE_INFO"),

	CASH_BANK_CARD_INFO(2,"CASH_BANK_CARD_INFO"),

	OTHER_USER_INFO(3,"OTHER_USER_INFO"),

	CLOSE_INFO(4,"CLOSE_INFO"),

	COMMODITY_INFO(5,"COMMODITY_INFO"),

	COMMODITY_PRICE_INFO(6,"COMMODITY_PRICE_INFO"),

	EXCHANGE_ACCESS_TO_GOLD_INFO(7,"EXCHANGE_ACCESS_TO_GOLD_INFO"),

	EXCHANGE_FUNDS_INFO(8,"EXCHANGE_FUNDS_INFO"),

	EXCHANGE_INFO(9,"EXCHANGE_INFO"),

	EXCHANGE_PARAM_SETTING(10,"EXCHANGE_PARAM_SETTING"),

	EXCHANGE_RED_SERIAL_INFO(11,"EXCHANGE_RED_SERIAL_INFO"),

	EXCHANGE_FEE_SERIAL_INFO(12,"EXCHANGE_FEE_SERIAL_INFO"),

	MEMBER_ACCESS_TO_GOLD_INFO(13,"MEMBER_ACCESS_TO_GOLD_INFO"),

	MEMBER_FREEZE_AMOUNT(14,"MEMBER_FREEZE_AMOUNT"),

	MEMBER_FREEZE_IN_USER(15,"MEMBER_FREEZE_IN_USER"),

	MEMBER_FUNDS_INFO(16,"MEMBER_FUNDS_INFO"),

	MEMBER_INFO(17,"MEMBER_INFO"),

	MEMBER_SERIAL_IN_USER(18,"MEMBER_SERIAL_IN_USER"),

	MEMBER_SERIAL_INFO(19,"MEMBER_SERIAL_INFO"),

	PRODUCT_INFO(21,"PRODUCT_INFO"),

	TICKET_INFO(22,"TICKET_INFO"),

	USER_ACCESS_TO_GOLD_INFO(23,"USER_ACCESS_TO_GOLD_INFO"),

	USER_COMMODITY_HOLD_INFO(24,"USER_COMMODITY_HOLD_INFO"),

	USER_FREEZE_AMOUNT_INFO(25,"USER_FREEZE_AMOUNT_INFO"),

	USER_FUNDS_INFO(26,"USER_FUNDS_INFO"),

	USER_INFO(27,"USER_INFO"),

	USER_SERIAL_INFO(28,"USER_SERIAL_INFO"),

	WEIXIN_USER_INFO(29,"WEIXIN_USER_INFO"),

	USER_REAL_INFO(30,"USER_REAL_INFO"),

	AGENT_INFO(31,"AGENT_INFO"),

	EXCHANGE_FEE_SERIAL_IN_USER(32,"EXCHANGE_FEE_SERIAL_IN_USER"),

	EXCHANGE_RED_SERIAL_IN_USER(33,"EXCHANGE_RED_SERIAL_IN_USER"),

	FUNDS_CHECK_RESULT(34, "FUNDS_CHECK_RESULT"),

	EXCHANGE_FUNDS_CHECK_INFO(35, "EXCHANGE_FUNDS_CHECK_INFO"),

	MEMBER_FUNDS_CHECK_INFO(36, "MEMBER_FUNDS_CHECK_INFO"),

	USER_FUNDS_CHECK_INFO(37, "USER_FUNDS_CHECK_INFO"),

	JSCLEAR_CHECK_RESULT(38, "JSCLEAR_CHECK_RESULT"),

	JSCLEAR_USER_DETAIL(39, "JSCLEAR_USER_DETAIL"),

	JSCLEAR_CHECK_DEAL(40, "JSCLEAR_CHECK_DEAL"),

	JSCLEAR_CHECK_ORDER(41, "JSCLEAR_CHECK_ORDER"),

	USER_RED_CHECK_INFO(42, "USER_RED_CHECK_INFO"),

	SINGLE_ACCOUNT_RECORD(43, "SINGLE_ACCOUNT_RECORD"),

	MULTI_ACCOUNT_RECORD(44, "MULTI_ACCOUNT_RECORD"),
	;

	private int id;
	private String name;
	
	TableEnum(int id, String name) {
		this.id = id;
		this.name = name;
		TableUtils.add(this);
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
}
