
package cn.sw.study.common.test.webservice.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TestJdkWebServiceService", targetNamespace = "http://webservice.test.common.study.sw.cn/", wsdlLocation = "http://localhost:8088/TestJdkWebService?wsdl")
public class TestJdkWebServiceService
    extends Service
{

    private final static URL TESTJDKWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException TESTJDKWEBSERVICESERVICE_EXCEPTION;
    private final static QName TESTJDKWEBSERVICESERVICE_QNAME = new QName("http://webservice.test.common.study.sw.cn/", "TestJdkWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8088/TestJdkWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TESTJDKWEBSERVICESERVICE_WSDL_LOCATION = url;
        TESTJDKWEBSERVICESERVICE_EXCEPTION = e;
    }

    public TestJdkWebServiceService() {
        super(__getWsdlLocation(), TESTJDKWEBSERVICESERVICE_QNAME);
    }

    public TestJdkWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TESTJDKWEBSERVICESERVICE_QNAME, features);
    }

    public TestJdkWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, TESTJDKWEBSERVICESERVICE_QNAME);
    }

    public TestJdkWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TESTJDKWEBSERVICESERVICE_QNAME, features);
    }

    public TestJdkWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestJdkWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TestJdkWebService
     */
    @WebEndpoint(name = "TestJdkWebServicePort")
    public TestJdkWebService getTestJdkWebServicePort() {
        return super.getPort(new QName("http://webservice.test.common.study.sw.cn/", "TestJdkWebServicePort"), TestJdkWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestJdkWebService
     */
    @WebEndpoint(name = "TestJdkWebServicePort")
    public TestJdkWebService getTestJdkWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.test.common.study.sw.cn/", "TestJdkWebServicePort"), TestJdkWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TESTJDKWEBSERVICESERVICE_EXCEPTION!= null) {
            throw TESTJDKWEBSERVICESERVICE_EXCEPTION;
        }
        return TESTJDKWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
