
package cn.sw.study.common.test.webservice.client;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TestJdkWebService", targetNamespace = "http://webservice.test.common.study.sw.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TestJdkWebService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://webservice.test.common.study.sw.cn/", className = "cn.sw.study.common.test.webservice.client.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://webservice.test.common.study.sw.cn/", className = "cn.sw.study.common.test.webservice.client.SayHelloResponse")
    @Action(input = "http://webservice.test.common.study.sw.cn/TestJdkWebService/sayHelloRequest", output = "http://webservice.test.common.study.sw.cn/TestJdkWebService/sayHelloResponse")
    public String sayHello();

}
